### PR TITLE
R-wrappers directory

### PR DESCRIPTION
**Pull request by SAbdulah**
1- add new r-wrappers directory to mimic ExaGeoStat functions (GenerateZ - MLE) for now.

2- add Makefile to build Shared lib to be used by R functions.

### CODE REVIEW

**Comment by SAbdulah** [comment]
@ltaiefhatem @egonzalf. Please merge this pull request. Please keep the branch for now.

**Comment by egonzalf** [comment]
I have a comment:
you are defining 4 wrappers:
- rexageostat_init
- rexageostat_finalize
- rexageostat_gen_z
- rexageostat_likelihood

Of those, the first 2 have are in the original code as:
- exageostat_init
- exageostat_finalize

but you don't wrap them. You copy their functionality, so why don't call directly the original function?.

The other 2 functions I did not find the equivalent.

**Comment by SAbdulah** [comment]
I see. The main point here is to separate r-wrapper functions from the original ones.

**Comment by SAbdulah** [comment]
@egonzalf

**Pull request merged**
